name: 'Setup Supabase Environment'
description: 'Sets up Supabase CLI and starts local Supabase instance'

outputs:
  supabase_url:
    description: 'The URL of the Supabase instance'
    value: ${{ steps.start-supabase.outputs.supabase_url }}
  anon_key:
    description: 'The anonymous key for Supabase API'
    value: ${{ steps.start-supabase.outputs.anon_key }}

runs:
  using: "composite"
  steps:
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Start Supabase
      id: start-supabase
      shell: bash
      run: |
        supabase start
        echo "supabase_url=http://localhost:54321" >> $GITHUB_OUTPUT
        echo "anon_key=$(supabase status -o json | jq -r '.api.service_api_keys[1].api_key')" >> $GITHUB_OUTPUT

    - name: Verify Supabase is running
      shell: bash
      run: supabase status
