name: 'Setup Playwright Environment'
description: 'Sets up Playwright for E2E testing'

runs:
  using: "composite"
  steps:
    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install --with-deps chromium

    - name: Wait for server to start
      shell: bash
      run: npx wait-on http://localhost:4321 -t 60000
