name: Build and Test

on:
  # Uruchamianie po push do mastera
  push:
    branches: [master]
  # Uruchamianie ręczne
  workflow_dispatch:

jobs:
  # Job dla testów jednostkowych i buildu
  test-and-build:
    name: Run Tests and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node-js

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run build
        run: npm run build
        env:
          PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL || 'http://localhost:54321' }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY || 'placeholder-for-ci' }}

  # Osobny job dla testów E2E (Playwright)
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node-js

      - name: Setup Supabase environment
        id: supabase
        uses: ./.github/actions/setup-supabase

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run development server
        run: npm run dev:e2e &
        env:
          PUBLIC_SUPABASE_URL: ${{ steps.supabase.outputs.supabase_url }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ steps.supabase.outputs.anon_key }}
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:4321
          CI: true

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          PUBLIC_SUPABASE_URL: ${{ steps.supabase.outputs.supabase_url }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ steps.supabase.outputs.anon_key }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
